### PR TITLE
Defunct DigitalOcean functions

### LINKED ISSUE #593: Port existing `analogsea` / digital ocean code to a new `plumberDigitialOcean` R package
The code on CRAN has been broken for at least 6 months.  Plumber can not update as fast as `analogsea` might want to update. 

This code was originally set up for showing how a toy example of plumber can be deployed to Digital Ocean.  However, this adds extra dependencies and is out of scope for the `plumber` R package.

I propose that 
* `plumber` Digital Ocean code be ported to an external R package (`plumberDigitalOcean`?). It could then be used in the `plumber` documentation on how to host on Digital Ocean.  
* The existing plumber functions should not really exist in outside scripts, so they may be gutted to proved a single message of `"Please visit USER/plumberDigitalOcean to run FUNC()"`. 
  * Maybe paired with message `remotes::install_github("USER/plumberDigitalOcean"); plumberDigitalOcean::FUNC()`

------------------

I would welcome this breaking change.

### PR DESCRIPTION
**Pull request by schloerke**
Fixes #593 
Updates of #621

PR task list:
- [x] Update NEWS
- [x] Add tests
- [x] Update documentation with `devtools::document()`

### CODE REVIEW

File: R/digital-ocean.R [hunk 1]
```diff
@@ -1,470 +1,42 @@
...
-  writeLines(forward, forwardfile)
-
-  analogsea::droplet_upload(droplet, forwardfile, "/etc/nginx/sites-available/plumber-apis/_forward.conf")
-
-  # TODO: add this as a catch()
-  file.remove(forwardfile)
-
-  invisible(droplet)
+#' @rdname digitalocean
+do_forward <- function(...) {
```
Comment (cpsievert) [inline R/digital-ocean.R:28]: We should be nicer about these deprecations. Specifically, I'm worried about the `library(plumberDeploy); library(plumber)` case

File: R/digital-ocean.R [hunk 2]
```diff
@@ -58,6 +58,10 @@ plumber_deploy_helper <- function(fn_name, args, new_fn_name = fn_name) {
...
   lifecycle::deprecate_warn("1.0.0", cur_fn, new_fn)
 
-  fn <- getFromNamespace(fn_name, "plumberDeploy")
+  fn <- utils::getFromNamespace(fn_name, "plumberDeploy")
   do.call(fn, args)
 }
+
+plumberDeploy_is_installed <- function() {
+    nzchar(system.file(package = "plumberDeploy"))
+}
```
Comment (cpsievert) [inline R/digital-ocean.R:67]: Maybe it's time to have something like `shiny:::is_available`
